name: Build Pipeline Frontend
on:
  push:
    branches:
      - java-final-ui
jobs:
  Build:
      name: Build-Image
      runs-on: ubuntu-latest
      steps:
        # {2}
        - name: Checkout the source code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Login Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Extract version
          id: extract_version
          run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

        - name: Build Image
          uses: docker/build-push-action@v5
          with:
            file: Dockerfile
            context: .
            push: true
            platforms: linux/amd64
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/btl_java_frontend:${{ steps.extract_version.outputs.VERSION }}, ${{ secrets.DOCKER_HUB_USERNAME }}/btl_java_frontend:latest

