name: Build Pipeline Frontend
on:
  push:
    branches:
      - main
jobs:
  Build:
      name: Project Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 20 ]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      steps:
        # {2}
        - name: Checkout the source code
          uses: actions/checkout@v4

        # {3}
        - name: Setup Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: package-lock.json

        # {4}
        - name: Install dependencies
          run: npm ci
        # {6}
        - name: Build
          run: npm run build
        - name: Login Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Extract version
          id: extract_version
          run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

        - name: Build Image
          uses: docker/build-push-action@v5
          with:
            file: Dockerfile
            context: .
            push: true
            platforms: linux/amd64
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/btl_java_frontend:${{ steps.extract_version.outputs.VERSION }}, ${{ secrets.DOCKER_HUB_USERNAME }}/btl_java_frontend:latest

